apiVersion: v1
kind: ConfigMap
metadata:
  name: casdoor-config
  namespace: casdoor
data:
  app.conf: |
    appname = casdoor
    httpport = 8000
    runmode = dev
    SessionOn = true
    copyrequestbody = true
    driverName = mysql
    dataSourceName = root:casdoor123@tcp(mysql-svc:3306)/
    dbName = casdoor
    tableNamePrefix =
    showSql = false
    redisEndpoint =
    defaultStorageProvider =
    isCloudIntranet = false
    authState = "casdoor"
    socks5Proxy = ""
    verificationCodeTimeout = 10
    initScore = 2000
    logPostOnly = true
    origin = "http://localhost:8000"
    staticBaseUrl = "https://cdn.casbin.org"
